# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLPhotoCropDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CLPhotoCropDemo
  pod 'CLPhotoCrop', :path => "../"

  target 'CLPhotoCropDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CLPhotoCropDemoUITests' do
    # Pods for testing
  end

end
